### ISSUE TITLE
文件夹名字不能带空格

### ISSUE THREAD

**Issue by aprilyzl0405** [XadillaX/nyaa-nodejs-demo#6]
## 操作系统
MACOS 或 Linux

## 报错
```
make: Entering directory '/home/develop/nyaa-nodejs-demo/36. napi/build'
  SOLINK_MODULE(target) Release/obj.target/node_modules/node-addon-api/src/nothing.node
  COPY Release/nothing.node
  CXX(target) Release/obj.target/addon/addon.o
g++: error: napi/node_modules/node-addon-api/src: No such file or directory
g++: error: napi/node_modules/node-addon-api: No such file or directory
addon.target.mk:114: recipe for target 'Release/obj.target/addon/addon.o' failed
make: *** [Release/obj.target/addon/addon.o] Error 1
make: Leaving directory '/home/develop/nyaa-nodejs-demo/36. napi/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/develop/.npm-global/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/home/develop/.nvs/node/12.13.0/x64/bin/node" "/home/develop/.npm-global/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/develop/nyaa-nodejs-demo/36. napi
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v6.0.0
gyp ERR! not ok 
```

## 原因
binding.gyp中类似
```
"include_dirs": [ "<!@(node -p \"require('node-addon-api').include\")" ]
```
展开后头文件查找路径是以字符串存在的，所以导致查找头文件时因为空格导致查找头文件路径不对,下面是我的展开
```
'"/home/develop/nyaa-nodejs-demo/36. napi/node_modules/node-addon-api/src" "/home/develop/nyaa-nodejs-demo/36. napi/node_modules/node-addon-api"'
```
将36.\ napi修改为 36.napi后就修复了，因此这里应该的确是文件夹名字空格的原因。

**Comment by XadillaX** [comment]
我在写的时候都是没问题的。你的 Node.js 和系统分别是什么版本的？

**Comment by XadillaX** [comment]
我在写的时候都是没问题的。你的 Node.js 和系统分别是什么版本的？
